Docs(web-twig, web-react): Improve `Modal` documentation regarding `ScrollView` and optional title
lmc-eu/spirit-design-system pull request #1025
Opened 2023-08-29 11:23 UTC by adamkudrna

https://jira.lmc.cz/browse/DS-876

2023-08-29 12:20 UTC, crishpeen requested changes

2023-08-29 12:20 UTC, crishpeen commented on packages/web-twig/src/Resources/components/Modal/README.md
> +<ScrollView data-spirit-toggle="scrollView" indicators="both">
```suggestion
<ScrollView data-spirit-toggle="scrollView" overflowDecorators="both">
```

2023-08-29 12:20 UTC, crishpeen commented on packages/web-twig/src/Resources/components/Modal/README.md
> +    <ScrollView data-spirit-toggle="scrollView" indicators="both">
```suggestion
    <ScrollView data-spirit-toggle="scrollView" overflowDecorators="both">
```

2023-08-29 12:20 UTC, crishpeen commented on packages/web-twig/src/Resources/components/Modal/stories/ModalScrollingLongContent.twig
> +            <ScrollView data-spirit-toggle="scrollView" indicators="both">
```suggestion
            <ScrollView data-spirit-toggle="scrollView" overflowDecorators="both">
```

2023-08-29 12:49 UTC, crishpeen approved these changes

2023-08-30 22:29 UTC, pavelklibani approved these changes

2023-09-05 09:41 UTC, dlouhak commented on packages/web-react/src/components/Modal/README.md
> +  <ModalBody>…Long content…</ModalBody>
?

```suggestion
  <ModalBody>
      …Long content…
  </ModalBody>
```

2023-09-05 10:55 UTC, dlouhak commented on packages/web-react/src/components/Modal/README.md
> +To make content overflow more obvious to users, you can wrap the ModalBody content in a [ScrollView][scroll-view] that
? 

```suggestion
To make content overflow more obvious to users, you can wrap the `ModalBody` content in a [ScrollView][scroll-view] that
```

2023-09-06 09:26 UTC, literat commented on packages/web-react/src/components/Modal/README.md
> +  <ModalBody>…Long content…</ModalBody>
Fixed.

2023-09-06 09:49 UTC, merged