Fix(web): No remove spacing on first elememnt on stack with intermedi…
lmc-eu/spirit-design-system pull request #1041
Opened 2023-09-05 13:40 UTC by chadimaOndrej

…ate divaders

## Description

### Additional context

### Issue reference

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/lmc-eu/spirit-design-system/blob/main/CONTRIBUTING.md).
- [ ] Follow the [PR Title/Commit Message Convention](https://github.com/lmc-eu/spirit-design-system/blob/main/CONTRIBUTING.md#commit-conventions).
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-09-06 07:19 UTC, vmilersky approved these changes

2023-09-07 09:52 UTC, dlouhak commented on packages/web/src/scss/components/Stack/_Stack.scss
> -    padding-block-start: 0;
This line of the code shouldn't be part of the intermediate dividers styles – only in the combination with `Stack--hasSpacing` (included in the styles above). So I assume, this PR is bug fix, not BC, right?

2023-09-07 09:52 UTC, dlouhak approved these changes

2023-09-07 14:47 UTC, crishpeen requested changes

2023-09-07 14:47 UTC, crishpeen commented on packages/web/src/scss/components/Stack/_Stack.scss
> -    padding-block-start: 0;
It looks like it, so please remove ti as well. Otherwise it is probably a bug, so thanks for the fix.

2023-09-13 06:26 UTC, literat approved these changes
LGTM, but I am letting @adamkudrna decide if this is ok.

2023-09-26 09:29 UTC, adamkudrna approved these changes

2023-09-26 09:36 UTC, adamkudrna commented
Please fix the commit message to be more 🇬🇧 

> Prevent `Stack` with inner dividers from suppressing vertical spacing of outer items

🎉

2023-09-26 09:41 UTC, crishpeen approved these changes

2023-09-26 10:03 UTC, merged