Docs(web-react, web): Add TextField demo #DS-913
lmc-eu/spirit-design-system pull request #1070
Opened 2023-09-17 00:45 UTC by pavelklibani

## Description

TextField demos are now same in all packages

### Issue reference

[Demo: TextField má ve všech technologiích stejná dema](https://jira.lmc.cz/browse/DS-913)

2023-09-18 07:40 UTC, literat commented
![Screenshot 2023-09-18 at 9 37 50](https://github.com/lmc-eu/spirit-design-system/assets/2481010/1f458f1d-cdd7-47e6-a9b8-ffb440288ca3)
![Screenshot 2023-09-18 at 9 37 56](https://github.com/lmc-eu/spirit-design-system/assets/2481010/7b20d586-67bc-4eaa-a018-5018a4fe0ea8)
![Screenshot 2023-09-18 at 9 38 18](https://github.com/lmc-eu/spirit-design-system/assets/2481010/2f0f16d4-e25f-4ba1-a92f-86d12dd0d177)
![Screenshot 2023-09-18 at 9 38 35](https://github.com/lmc-eu/spirit-design-system/assets/2481010/c46a0d5f-b77b-474b-bc95-29d25737ae53)

There are some visual inconsistencies that must be solved. Maybe @crishpeen or @adamkudrna could help.

2023-09-18 07:42 UTC, literat requested changes
There are some visual changes that break the layout.

2023-09-19 15:02 UTC, literat approved these changes
LGTM ❤️

2023-09-21 07:53 UTC, crishpeen approved these changes

2023-09-21 11:06 UTC, merged