Improve docs for both users and contributors
lmc-eu/spirit-design-system pull request #108
Opened 2021-12-31 20:30 UTC by adamkudrna

2022-01-03 09:00 UTC, literat requested changes

2022-01-14 19:02 UTC, adamkudrna commented on packages/design-tokens/README.md
> +.MyComponentThatMayGoToSpiritInFuture {
OK 🙂

2022-01-14 19:04 UTC, adamkudrna commented on packages/design-tokens/README.md
> +Simply put, if you are going to build a design system based on Spirit:
> In clearer, more direct, or more easily understandable terms. A set phrase used when discussing a complicated topic or situation.
>
> A: _"What the heck is a cholecystectomy?"_
> B: _"Simply put, it's the surgical removal of the gallbladder, something we do here at the hospital everyday. We'll take good care of your husband."_
> A: _"Simply put, he's a fool, and he never deserved you." B: "Well, don't mince words, Mom."_

https://idioms.thefreedictionary.com/simply+put

2022-01-17 06:55 UTC, literat approved these changes

2022-01-17 06:56 UTC, literat commented
@adamkudrna Please, run `format:fix` to reformat documents. Otherwise LGTM.

2022-01-17 16:45 UTC, merged