Feat(web): Accordion_itemHeader background blink
lmc-eu/spirit-design-system pull request #1559
Opened 2024-07-23 10:19 UTC by pavelklibani

- Do not blink on touch screens when cliking on the item header of the accordion

Solves DS-1365

## Description

### Additional context

### Issue reference

2024-07-30 15:46 UTC, adamkudrna requested changes
I tested it in mobile Safari and it works as expected, i.e. the header background doesn't flicker on interaction.

2024-07-30 15:46 UTC, adamkudrna commented on packages/web/src/scss/components/Accordion/_Accordion.scss
Please improve the commit message so it says what has been changed and why, as per our usual standards 🙂.

2024-08-06 08:45 UTC, pavelklibani commented on packages/web/src/scss/components/Accordion/_Accordion.scss
commit message updated

2024-08-06 09:19 UTC, crishpeen approved these changes

2024-08-06 09:31 UTC, adamkudrna approved these changes

2024-08-06 13:42 UTC, literat approved these changes
LGTM 👍

2024-08-06 13:57 UTC, merged