Feat(web): Introduce ActionGroup component #DS-1607
lmc-eu/spirit-design-system pull request #1832
Opened 2024-12-30 14:26 UTC by pavelklibani

## Description

### Additional context

### Issue reference

[Component ActionGroup | Web](https://jira.almacareer.tech/browse/DS-1607)

2024-12-31 11:43 UTC, curdaj commented on packages/web/src/scss/components/ActionGroup/ActionGroup.scss
> +    justify-content: left;
`justify-content: start`?

2025-01-07 16:20 UTC, adamkudrna requested changes

2025-01-07 16:20 UTC, adamkudrna commented on packages/web/src/scss/components/ActionGroup/README.md
We agreed in person to:

1. **not** implement the `ActionGroup` component in the `web` package **at all**,
2. instead, extend the `Flex` component:
   1. extend the Direction Dictionary with `DirectionExtended` which extends `Direction` with `horizontalReversed` and `verticalReversed`,
   2. deprecate `row` and `column` layouts of the `Flex` component in favor of the `DirectionExtended` dictionary, create codemod in React,
3. in React, reuse the updated `Flex` component to create the `ActionGroup` component.

2025-01-08 10:02 UTC, literat commented on packages/web-react/src/components/ActionGroup/README.md
**issue (blocking):** We have nothing to say here?

2025-01-08 10:11 UTC, literat commented on packages/web-react/src/components/ActionGroup/demo/ColumnLayout.tsx
> +    <ActionGroup direction="column">
**suggestion (blocking):** I am not quite satisfied with the naming. I expect the `direction` is from left to right, up and down, not `column` or `row`.

Maybe `orientation` as I saw it in [Adobe Spectrum Button Group](https://spectrum.adobe.com/page/button-group/#Orientation) would sound better. Of course with values like `horizontal` or `vertical`. And I think `horizontal-reversed` or `vertical-reversed` work as well.

2025-01-08 10:19 UTC, literat commented on packages/web/src/scss/components/ActionGroup/README.md
Just for the naming. Isn't the `Orientation` with the values `vertical`/`horizontal` better than `Direction`? I think the "direction" suggests more from/to path than "orientation", which I understand as position on some point, e.g. a 360-degree circle (I hope this is understandable).

2025-01-08 10:21 UTC, literat commented on packages/web/src/scss/components/ActionGroup/index.html
> +        <a href="#" role="button" class="Button Button--primary Button--medium">Primary Action</a>
**suggestion:** Maybe @adamkudrna wants to suggest this:
```suggestion
        <button class="Button Button--primary Button--medium">Primary Action</a>
```

2025-01-09 14:25 UTC, adamkudrna commented on packages/web/src/scss/components/ActionGroup/index.html
> +        <a href="#" role="button" class="Button Button--primary Button--medium">Primary Action</a>
Either of these, they are both correct, it doesn't matter. Just let's not use `<a role="button">` 🙂.

2025-01-09 14:28 UTC, adamkudrna commented on packages/web-react/src/components/ActionGroup/README.md
@pavelklibani left the README intentionally empty because he anticipated we would decide to discard the `web` component.

2025-01-14 14:35 UTC, pavelklibani commented
closed in favor of https://github.com/lmc-eu/spirit-design-system/pull/1843

2025-01-14 14:35 UTC, closed without merging