Feat(web): Add text and background color utilities #DS-189
lmc-eu/spirit-design-system pull request #225
Opened 2022-03-28 10:37 UTC by crishpeen

2022-03-28 12:54 UTC, literat approved these changes

2022-03-31 16:29 UTC, adamkudrna requested changes

2022-03-31 16:29 UTC, adamkudrna commented on packages/web/src/settings/_utilities.scss
> +            inverted: tokens.$background-interactive-active,
```suggestion
            inverted: tokens.$background-inverted,
```

2022-03-31 16:29 UTC, adamkudrna commented on packages/web/src/settings/_utilities.scss
> +@use 'sass:meta';
It doesn't seem to be used.

2022-04-05 07:32 UTC, adamkudrna approved these changes

2022-04-05 08:21 UTC, merged