Feat(web): Add support for TextField's size attribute #DS-154
lmc-eu/spirit-design-system pull request #282
Opened 2022-04-19 09:40 UTC by ondrej-kaspar

2022-04-28 09:51 UTC, adamkudrna requested changes
Cool! Could you just show the feature in `examples/web/index.html`? Otherwise LGTM ✅.

2022-04-28 09:51 UTC, adamkudrna commented on packages/web/src/scss/components/TextField/README.md
> +###`size` attribute
```suggestion
### `size` attribute
```

2022-04-29 07:37 UTC, literat approved these changes
LGTM

2022-05-02 15:41 UTC, adamkudrna approved these changes

2022-05-02 15:48 UTC, merged