Docs(web): Improve previews for both development and Supernova context
lmc-eu/spirit-design-system pull request #424
Opened 2022-08-12 18:56 UTC by adamkudrna

New homepage design:

<img width="1848" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/184425174-1f20c213-6cbd-4957-ae3a-9cb4f661edce.png">

2022-08-12 18:57 UTC, adamkudrna commented on packages/web/src/scss/components/Alert/index.html
> -  <h2 class="typography-heading-medium-text mt-1100 mb-800">Alert</h2>
Main headings are not needless for both development and Supernova.

2022-08-12 18:58 UTC, adamkudrna commented on packages/web/src/scss/helpers/index.html
> +    <h2 class="docs-Heading">Accessibility</h2>
Added missing docs for some helpers.

2022-08-15 07:43 UTC, literat requested changes

2022-08-15 07:43 UTC, literat commented on packages/web/vite.config.ts
> +      runtimeOptions: {
Please add some notes to `CONTRIBUTING.md` about places that should developer update when adding a new component. Thanks :-)

2022-08-18 16:02 UTC, crishpeen approved these changes
Great work. LGTM.

I would love to see one improvement, but we can do it in another PR/issue. How about two separate layouts for components? One without (currently plain) anything, just the component content. This could be used in Supernova docs. And another with a header and link to all components. This would be for development and for the demo website. 

What do you think? On build, we would generate both from the same indexes. I think @literat mentioned that it should be possible.

2022-08-22 09:03 UTC, literat commented on packages/web/vite.config.ts
> +      runtimeOptions: {
I've added mention in `File Structure`.

2022-08-22 09:04 UTC, literat approved these changes

2022-08-22 09:14 UTC, literat commented
> What do you think? On build, we would generate both from the same indexes. I think @literat mentioned that it should be possible.

I've created an issue for this: https://github.com/lmc-eu/spirit-design-system/issues/432

2022-08-22 09:24 UTC, merged