Feature/ds 305 icons header
lmc-eu/spirit-design-system pull request #466
Opened 2022-09-06 13:34 UTC by crishpeen

2022-09-06 15:24 UTC, literat requested changes
LGTM, but not sure about the removing of `aria-hidden="true"`. Maybe you should pass it to the `Icon` component.

2022-09-06 15:24 UTC, literat commented on packages/web-react/src/components/Header/NavbarClose.tsx
> -      <span className={classNames(headerIconClass, headerIconCloseClass)} aria-hidden="true" />
What about that `aria-hidden="true"`?

2022-09-09 06:28 UTC, literat approved these changes
LGTM

2022-09-13 09:39 UTC, adamkudrna approved these changes

2022-09-13 09:39 UTC, adamkudrna commented on packages/web-react/src/components/Header/NavbarClose.tsx
> +      <Icon name="close" aria-hidden="true" />
We talked about moving `aria-hidden="true"` into the `Icon` component, could you please fix it?

2022-09-13 09:39 UTC, adamkudrna commented on packages/web/src/scss/components/Header/_theme.scss
> +$close-color: tokens.$action-inverted-default;
```suggestion
$close-button-color: tokens.$action-inverted-default;
```

2022-09-13 12:16 UTC, merged