Fix(web): Fix underlined Link
lmc-eu/spirit-design-system pull request #467
Opened 2022-09-06 13:56 UTC by dlouhak

Now looks Link component with `text-decoration: underline` same as in Figma! 🎉 

Figma
![image](https://user-images.githubusercontent.com/33354913/188650598-8da26065-db90-4474-9b8b-d4154dabc7fa.png)

Web
- before:
![image](https://user-images.githubusercontent.com/33354913/188652158-15b34227-2b48-41f5-b2c5-497a4e4066f4.png)
- after:
![image](https://user-images.githubusercontent.com/33354913/188650262-d4436136-7bdc-413d-a220-da416a93ba9e.png)

Unfortunately, I still don't know what causes the difference in rendered text styles between Figma and web. 😞

2022-09-08 08:13 UTC, vmilersky commented
I think there is enough support in browsers, I'm OK with that 👍

2022-09-08 08:14 UTC, vmilersky approved these changes

2022-09-13 12:48 UTC, adamkudrna requested changes
Thank you for bringing this up! It still needs attention in few details, but it already looks great.

2022-09-13 12:48 UTC, adamkudrna commented on packages/web/src/scss/helpers/_links.scss
>      text-decoration: underline;
Keep in mind this is a shorthand property for all `text-decoration-*` properties. Now we need to be more explicit with `text-decoration-line` everywhere we work with a visible decoration, mainly in headings. (`text-decoration: none` should be mostly fine.)

![obrazek](https://user-images.githubusercontent.com/5614085/189904099-0b9ec79f-723c-440f-875b-42ababfcf929.png)

2022-09-22 09:44 UTC, adamkudrna approved these changes
Cool!

2022-09-22 09:44 UTC, adamkudrna commented on packages/web/src/scss/helpers/_links.scss
>  [class*='typography-heading'] a {
I only think our future version of Stylelint config is not going to like this because of `no-descending-specificity`. But it works either way.

2022-09-22 10:07 UTC, merged