BREAKING CHANGES(web-react): Do not provide non-existing CSS class `Tabs-content` in `Tabs` hook
lmc-eu/spirit-design-system pull request #495
Opened 2022-09-15 17:20 UTC by adamkudrna

Migration: Delete `content` class name provided by the `useTabsStyleProps` hook. There is no styling applied to it.

2022-09-15 19:29 UTC, literat requested changes
Please, fix also the tests. There is a usage of `content` in `useTabsStyleProps.test.tsx`.

2022-10-06 16:03 UTC, adamkudrna commented
> Please, fix also the tests. There is a usage of `content` in `useTabsStyleProps.test.tsx`.

There you see it! 🙂 It's a result of sticking class names together in the code, full-text doesn't find it 🙂.

```js
`${tabsClass}-content`
```

2022-10-06 20:01 UTC, literat commented
> There you see it! 🙂 It's a result of sticking class names together in the code, full-text doesn't find it 🙂.

That's the difference between relying on IDE and knowing how it works :-) I always choose the path broken test -> what it is using -> how it works than just search for a string ;-)

2022-10-06 20:04 UTC, literat commented on packages/web-react/src/components/Tabs/useTabsStyleProps.tsx
>        root: tabsClass,
Maybe if you prefer alphabetical order you also move the `root` class prop ;-)

2022-10-06 20:04 UTC, literat approved these changes
Good job 👍

2022-10-07 09:53 UTC, adamkudrna commented
> I always choose the path broken test -> what it is using

It doesn't have to be always clear with CSS as it is often disconnected from its usages… I'll be happy to talk about it later 🙂.

2022-10-07 10:30 UTC, merged