Feat(web-react): React Modal implementation #DS-331
lmc-eu/spirit-design-system pull request #515
Opened 2022-10-03 13:34 UTC by tomassychra

# Jira issue [DS-331](https://jira.lmc.cz/browse/DS-331)

Implementation of Modal component for REACT

## 👉 What was done

1. React component & documentation & Stories
  - Modal
  - ModalHeader
  - ModalBody
  - ModalFooter

2022-10-03 21:47 UTC, dlouhak commented
Before we start doing code review, could you please:
- Fix lint errors.
- Following the retrospective from 23.9. I would separate this task into smaller commits or event better to separated PRs according to the modifications in the packages (web, web-react).
- Check if the Modal component behaves correctly? I'm looking at Storybook and it seems broken to me.

Thanks. 😊

2022-10-05 07:34 UTC, literat commented
Looking at https://deploy-preview-515--spirit-design-system-storybook.netlify.app/?path=/docs/components-modal--modal and there is no Modal rendered and toggling does not work. Please, check it.

2022-10-05 07:49 UTC, literat requested changes

2022-10-05 07:49 UTC, literat commented on packages/web-react/docs/stories/examples/LoginForm.stories.tsx
> +import * as React from 'react';
Why are you changing this? I think it is not necessary.

2022-10-05 07:49 UTC, literat commented on packages/web-react/src/components/Modal/Modal.tsx
> +    UNSAFE_style,
Please, move logic with style and class handling into `useModalStyleProps`. For example look at `useAlertStyleProps.` All components must be composable.

2022-10-05 07:49 UTC, literat commented on packages/web-react/src/components/Modal/ModalCloseButton.tsx
> +      <IconsProvider value={icons}>
This does not belong to this place. Use Icon directly but Provider you must use in an example like Storybook. Icons are interchangeable and now you are fixing them to Spirit Icons only.

2022-10-05 07:49 UTC, literat commented on packages/web-react/src/components/Modal/Modal.tsx
> +  const modal = createElement(
Why are you using `createElement` when you can just use JSX?

2022-10-05 07:49 UTC, literat commented on packages/web-react/src/components/Modal/ModalHeader.tsx
> +    className: [modalHeaderClass, UNSAFE_className].join(' '),
Please use `classnames` library instead of joining.

2022-10-05 07:49 UTC, literat commented on packages/web-react/src/components/Modal/README.md
> +## SpiritModalProps
Please see a heading level structure in `Tabs` for instance. We are using component name for heading and then `**Available props**`. We should be consistent.

2022-10-07 12:20 UTC, closed without merging