DS-56 Feat: Add react implementation of component Tag
lmc-eu/spirit-design-system pull request #60
Opened 2021-10-21 13:03 UTC by janicekt

Add react implementation of component Tag and add into storybook examples

2021-11-22 11:01 UTC, literat requested changes

2021-11-22 11:01 UTC, literat commented on packages/web-react/src/components/Tag/Tag.tsx
> +export type TagProps = WithChildren<{
Use `interface`, please.

2021-11-24 08:14 UTC, janicekt commented on packages/web-react/src/components/Tag/Tag.tsx
> +export type TagProps = WithChildren<{
changed

2021-11-24 09:06 UTC, literat approved these changes

2021-11-26 13:21 UTC, merged