Docs(web): Improve `Accordion` README and demo preview
lmc-eu/spirit-design-system pull request #630
Opened 2023-01-10 19:12 UTC by adamkudrna

2023-01-10 20:17 UTC, literat requested changes
Nitpicking, anything else looks great.

2023-01-12 15:27 UTC, adamkudrna commented on packages/web/src/scss/components/Accordion/README.md
> +Accordion is a composition of multiple [**Collapse**][collapse] items. Depending
TextLint will tell us what's right 🙂.

2023-01-12 15:32 UTC, adamkudrna commented on packages/web/src/scss/components/Accordion/README.md
> +Accordion is a composition of multiple [**Collapse**][collapse] items. Depending
Actually not Text Lint, but MD lint… It's a question of personal preference, linters are fine with it. But I fixed it so we don't spend any more time talking about it 🙂.

2023-01-12 15:32 UTC, adamkudrna commented on packages/web/src/scss/components/Accordion/README.md
> +Put one or more accordion items into the accordion wrapper:
OK, thanks for pointing this out. There are more places, I fixed them all.

2023-01-12 15:41 UTC, literat approved these changes

2023-01-16 15:25 UTC, adamkudrna commented on packages/web/src/scss/components/Accordion/README.md
> +<article class="Accordion__item"></article>
Fix the closing tag

2023-01-16 15:26 UTC, adamkudrna commented on packages/web/src/scss/components/Accordion/README.md
> +  - Accordion item (one or more)
```suggestion
  - Accordion item (one or, typically, more)
```

2023-01-24 14:06 UTC, merged