Feat(web-react): Export all types in main index too #DS-532
lmc-eu/spirit-design-system pull request #637
Opened 2023-01-12 12:24 UTC by crishpeen

2023-01-12 14:44 UTC, literat commented on packages/web-react/src/types/index.ts
> +export * from './main';
Please, recheck this. But I think that the content of `main.ts` is unused and therefor we should delete it.

2023-01-12 14:44 UTC, literat requested changes
We can delete `main.ts`.

2023-01-16 08:35 UTC, tomassychra approved these changes

2023-01-16 09:11 UTC, literat approved these changes

2023-01-16 11:36 UTC, merged