Feature/ds 572 dictionary heading
lmc-eu/spirit-design-system pull request #664
Opened 2023-01-31 19:41 UTC by crishpeen

2023-02-03 14:07 UTC, tomassychra approved these changes

2023-02-06 19:48 UTC, literat commented
@crishpeen Please update types accordingly the Text component.

2023-02-06 19:49 UTC, literat requested changes
Please update the types of the component accordingly to the Text component.

2023-02-06 20:27 UTC, literat approved these changes

2023-02-07 08:58 UTC, merged