Feature/ds 86 update colors
lmc-eu/spirit-design-system pull request #84
Opened 2021-12-01 10:12 UTC by crishpeen

2021-12-01 11:17 UTC, literat approved these changes

2021-12-01 14:18 UTC, adamkudrna requested changes
All is fine except the height of buttons.

2021-12-01 14:18 UTC, adamkudrna commented on packages/web/src/components/Button/_theme.scss
> +$line-height: tokens.$line-height-small;
According to Figma, buttons should be 40 px tall:

<img width="118" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/144249679-4661cb5f-eca5-4d90-880c-a2dca039ed72.png">

vs.

<img width="401" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/144249622-e7634269-8cbd-461b-af9f-3e0556bd66ba.png">

It seems that the sum of `line-height`, `border` and `padding` is smaller than we need…

2021-12-02 11:32 UTC, adamkudrna commented on packages/web/src/components/Button/_theme.scss
> +$line-height: tokens.$line-height-small;
<img width="209" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/144414314-569b0604-9409-41c6-9e93-d928007a8c10.png">

🤔

2021-12-02 15:44 UTC, adamkudrna commented on packages/web/src/components/Button/_theme.scss
> +$line-height: tokens.$line-height-small;
Let's solve it in a separate PR, we cannot let it block the merge of other changes in this PR.

2021-12-02 15:44 UTC, adamkudrna approved these changes

2021-12-02 15:46 UTC, merged