BREAKING CHANGE: Rename `message` prop to `validationText` in Form Fields #DS-676
lmc-eu/spirit-design-system pull request #888
Opened 2023-06-16 13:46 UTC by crishpeen

And make it dependent on `validationState`.

Sorry for the huge PR.

2023-06-19 07:37 UTC, literat commented on packages/web-twig/src/Resources/components/Field/README.md
> +# ValidationText
Not sure about this main heading. Maybe `Field` will be better based on the field structure and mention `ValidationText` as subcomponents.

2023-06-19 08:26 UTC, literat requested changes

2023-06-19 08:26 UTC, literat commented on packages/web/src/scss/components/CheckboxField/README.md
> +````
"````" -> "```"

2023-06-19 08:26 UTC, literat commented on packages/web/src/scss/components/CheckboxField/README.md
> +````html
Duplication of "````html"

2023-06-19 08:26 UTC, literat commented on packages/web/src/scss/components/RadioField/README.md
> +  <input type="radio" id="radiofieldDefaultChecked" class="RadioField__input" name="default" checked />
Do we want to have the same `name` in multiple examples?

2023-06-19 08:26 UTC, literat commented on packages/web/src/scss/components/RadioField/README.md
> +  <input type="radio" id="radiofieldDisabled" class="RadioField__input" disabled />
Missing `name`?

2023-06-21 06:18 UTC, literat commented
I have splitted this PR by commit/technology into three separate PRs, see https://github.com/lmc-eu/spirit-design-system/pull/899, https://github.com/lmc-eu/spirit-design-system/pull/900, https://github.com/lmc-eu/spirit-design-system/pull/901

2023-06-22 08:20 UTC, adamkudrna commented
Closing in favor of the individual PRs.

2023-06-22 08:20 UTC, closed without merging