Chore(repo): Remove Tomas Sychra and add Pavel Klibani to codeowners
lmc-eu/spirit-design-system pull request #929
Opened 2023-07-02 19:58 UTC by literat

## Description

### Additional context

### Issue reference

---

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/lmc-eu/spirit-desing-system/blob/main/CONTRIBUTING.md).
- [ ] Follow the [PR Title/Commit Message Convention](https://github.com/lmc-eu/spirit-desing-system/blob/main/CONTRIBUTING.md#commit-conventions).
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

2023-07-11 07:33 UTC, crishpeen requested changes

2023-07-17 08:01 UTC, literat commented on .github/CODEOWNERS
> +/packages/web                     @literat @adamkudrna @crishpeen @paveltechloop @lmc-eu/spirit-design-system
Fixed

2023-07-17 08:10 UTC, pavelklibani approved these changes

2023-07-17 08:15 UTC, crishpeen approved these changes

2023-07-17 08:15 UTC, merged