Docs(repo): Introduce form validations package in main README file
lmc-eu/spirit-design-system pull request #948
Opened 2023-07-21 12:18 UTC by literat

## Description

Add missing package to the table with provided packages in main readme.

### Additional context

### Issue reference

---

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/lmc-eu/spirit-desing-system/blob/main/CONTRIBUTING.md).
- [x] Follow the [PR Title/Commit Message Convention](https://github.com/lmc-eu/spirit-desing-system/blob/main/CONTRIBUTING.md#commit-conventions).
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

2023-07-21 13:04 UTC, crishpeen requested changes

2023-07-21 13:04 UTC, crishpeen commented on README.md
> +[sfv-badge]: https://img.shields.io/packagist/v/lmc/spirit-form-validations.svg?style=flat-square
```suggestion
[sfv-badge]: https://img.shields.io/npm/v/%40lmc-eu/spirit-form-validations.svg?style=flat-square
```

2023-07-21 13:04 UTC, crishpeen commented on README.md
> +[sfv-packagist]: https://packagist.org/packages/lmc/spirit-form-validations
```suggestion
[sfv-npm]: https://www.npmjs.com/package/@lmc-eu/spirit-form-validations
```

2023-07-21 13:41 UTC, literat commented on README.md
> +[sfv-badge]: https://img.shields.io/packagist/v/lmc/spirit-form-validations.svg?style=flat-square
🤦  Fixed.

2023-07-21 13:41 UTC, literat commented on README.md
> +[sfv-packagist]: https://packagist.org/packages/lmc/spirit-form-validations
🤦 Fixed.

2023-07-25 08:38 UTC, crishpeen approved these changes

2023-07-25 11:43 UTC, merged